version: '3.9'

services:
  web:
    container_name: mizunowa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production